# -*- coding: utf-8 -*-
"""DistilGPT2 Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltgbypBJZNNAlDidBziXRWU4l1_q4FCG
"""

!pip install transformers accelerate torch

import time
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name
).to("cuda" if torch.cuda.is_available() else "cpu")

prompt = "Write a Python function to add two numbers."

inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

start = time.time()

outputs = model.generate(
    **inputs,
    max_new_tokens=50
)

end = time.time()

generated_tokens = outputs.shape[1] - inputs.input_ids.shape[1]

execution_time = end - start

throughput = generated_tokens / execution_time

print("Generated Tokens:", generated_tokens)
print("Execution Time:", execution_time)
print("Throughput (tokens/sec):", throughput)

print(tokenizer.decode(outputs[0]))